### ISSUE TITLE
Support oidc roles in kubernetes

### ISSUE THREAD

**Issue by fams** [curityio/dynamodb-data-access-provider#13]
Hi folks,
We're migrating our eks  services from instance role using Kiam to OIDC using Web Identity Token. The plugin does not have a configuration directive to allow aws-sdk to find a proper credential. Is it possible to implement a way to use the default credentials chain or use web identity directly?

**Comment by pmhsfelix** [comment]
Hi,
Thanks for the issue.
We have plans to add that support in the near future.

**Comment by pmhsfelix** [comment]
Hi,

We've updated the DynamoDB authentication options on the plugin version bundled with the [7.3 release](https://developer.curity.io/release/7.3.0/release-notes) of Curity Identity Server. It now also supports both `WebIdentityTokenCredentialsProvider` and `DefaultCredentialsProvider`, which should address the added functionality being requested in this issue.
We've also updated the `dev` and `master` branches to be in sync with what is bundled with with Identity server (see https://github.com/curityio/dynamodb-data-access-provider/pull/14).

We are closing this issue because we believe the limitation is now solved.
Thanks for the feedback.
